In [0]:
import numpy as np

np어레이 만드는 법
1. Bracket을 활용

In [3]:
np.array([])

array([], dtype=float64)

In [5]:
np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.array([[1,2,3],[4,5,6],[7,8,9]], dtype= float)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [9]:
np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=np.float64)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

2. 함수를 이용해서 만드는 방법

In [13]:
np.zeros((2,2),dtype = int)

array([[0, 0],
       [0, 0]])

In [11]:
np.ones((3,1))

array([[1.],
       [1.],
       [1.]])

In [12]:
np.full((2,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.randn(2,2)

array([[ 0.64528434,  0.2181705 ],
       [-0.24818003, -0.70709158]])

In [25]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
a[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [27]:
n = int(input())
L = []

for i in range(n):
  name = input()
  score = int(input())
  L.append([name,score])

5
가
55
나
65
다
88
라
65
마
95


In [28]:
L


[['가', 55], ['나', 65], ['다', 88], ['라', 65], ['마', 95]]